export const headerLinks = [
  {
    id: 1,
    name: "Начало",
    url: "/",
  },
  {
    id: 2,
    name: "Публикуване",
    url: "/post",
  },
  {
    id: 3,
    name: "Търсене",
    url: "/search",
  },
  {
    id: 4,
    name: "Средна цена",
    url: "/average-price",
  },
  {
    id: 5,
    name: "Дилъри",
    url: "/dealers",
  },
  {
    id: 6,
    name: "Моите Обяви",
    url: "/my-listings",
  },
];

export const searchIcons = [
  {
    id: 1,
    name: "kola",
    link: "/searchIcons/kola.svg",
    linkActive: "/searchIcons/kolaWhite.svg",
    category: "Автомобили и Джипове",
  },
  {
    id: 2,
    name: "bus",
    link: "/searchIcons/bus.svg",
    linkActive: "/searchIcons/busWhite.svg",
    category: "Бусове",
  },
  {
    id: 3,
    name: "motor",
    link: "/searchIcons/motor.svg",
    linkActive: "/searchIcons/motorWhite.svg",
    category: "Мотори",
  },
  {
    id: 4,
    name: "kamion",
    link: "/searchIcons/kamion.svg",
    linkActive: "/searchIcons/kamionWhite.svg",
    category: "Камиони",
  },
  {
    id: 5,
    name: "kolelo",
    link: "/searchIcons/kolelo.svg",
    linkActive: "/searchIcons/koleloWhite.svg",
    category: "Велосипеди",
  },
  {
    id: 6,
    name: "lodka",
    link: "/searchIcons/lodka.svg",
    linkActive: "/searchIcons/lodkaWhite.svg",
    category: "Лодки",
  },
  {
    id: 7,
    name: "industrialni",
    link: "/searchIcons/industrialni.svg",
    linkActive: "/searchIcons/industrialniWhite.svg",
    category: "Индустриални",
  },
];

export const featuredCategories = [
  {
    id: 1,
    url: "/vehicles/newCars.png",
    name: "Нови Автомобили",
    offers: 11300,
  },
  {
    id: 2,
    url: "/vehicles/electricCars.png",
    name: "Е-Автомобили",
    offers: 68300,
  },
  {
    id: 3,
    url: "/vehicles/eBikes.png",
    name: "Е-Велосипеди",
    offers: 44300,
  },
  {
    id: 4,
    url: "/vehicles/leasing.png",
    name: "Лизингови",
    offers: 13300,
  },
  {
    id: 5,
    url: "/vehicles/usedCars.png",
    name: "Втора Употреба",
    offers: 23300,
  },
];

export const popularCategories = [
  {
    id: 1,
    url: "/vehicles/familyCars.png",
    name: "Семейни",
    offers: 11300,
  },
  {
    id: 2,
    url: "/vehicles/firstCars.png",
    name: "Първа кола",
    offers: 68300,
  },
  {
    id: 3,
    url: "/vehicles/luxuryCars.png",
    name: "Спортни",
    offers: 44300,
  },
  {
    id: 4,
    url: "/vehicles/ecoFriendly.png",
    name: "Екологични",
    offers: 13300,
  },
  {
    id: 5,
    url: "/vehicles/cityCars.png",
    name: "Градски",
    offers: 23300,
  },
];

export const vehicleTypes = [
  {
    id: 1,
    url: "/vehicleIcons/wagon.png",
    name: "Комби",
    offers: 11300,
  },
  {
    id: 2,
    url: "/vehicleIcons/saloon.png",
    name: "Седан",
    offers: 68300,
  },
  {
    id: 3,
    url: "/vehicleIcons/convertible.png",
    name: "Кабрио",
    offers: 44300,
  },
  {
    id: 4,
    url: "/vehicleIcons/suv.png",
    name: "Джип",
    offers: 13300,
  },
  {
    id: 5,
    url: "/vehicleIcons/sportsCar.png",
    name: "Спортни",
    offers: 23300,
  },
  {
    id: 6,
    url: "/vehicleIcons/van.png",
    name: "Ван/Минибус",
    offers: 23300,
  },
];

export const newestListings = [
  {
    id: 1,
    title: "BMW X3 3.0d xDrive M-Sport",
    kilometers: "190.500km",
    price: "58 000лв.",
    listingImg: "/car1.png",
    region: "обл. София-град",
    datePosted: "16:30PM, 03.12",
    isVip: true,
    isTop: false,
  },
  {
    id: 2,
    title: "BMW X3 3.0d xDrive M-Sport",
    kilometers: "190.500km",
    price: "58 000лв.",
    listingImg: "/car1.png",
    region: "обл. София-град",
    datePosted: "16:30PM, 03.12",
    isVip: true,
    isTop: false,
  },
  {
    id: 3,
    title: "BMW X3 3.0d xDrive M-Sport",
    kilometers: "190.500km",
    price: "58 000лв.",
    listingImg: "/car1.png",
    region: "обл. София-град",
    datePosted: "16:30PM, 03.12",
    isVip: false,
    isTop: true,
  },
  {
    id: 4,
    title: "BMW X3 3.0d xDrive M-Sport",
    kilometers: "190.500km",
    price: "58 000лв.",
    listingImg: "/car1.png",
    region: "обл. София-град",
    datePosted: "16:30PM, 03.12",
    isVip: false,
    isTop: true,
  },
  {
    id: 5,
    title: "BMW X3 3.0d xDrive M-Sport",
    kilometers: "190.500km",
    price: "58 000лв.",
    listingImg: "/car1.png",
    region: "обл. София-град",
    datePosted: "16:30PM, 03.12",
    isVip: false,
    isTop: false,
  },
  {
    id: 6,
    title: "BMW X3 3.0d xDrive M-Sport",
    kilometers: "190.500km",
    price: "58 000лв.",
    listingImg: "/car1.png",
    region: "обл. София-град",
    datePosted: "16:30PM, 03.12",
    isVip: false,
    isTop: true,
  },
  {
    id: 7,
    title: "BMW X3 3.0d xDrive M-Sport",
    kilometers: "190.500km",
    price: "58 000лв.",
    listingImg: "/car1.png",
    region: "обл. София-град",
    datePosted: "16:30PM, 03.12",
    isVip: false,
    isTop: false,
  },
  {
    id: 8,
    title: "BMW X3 3.0d xDrive M-Sport",
    kilometers: "190.500km",
    price: "58 000лв.",
    listingImg: "/car1.png",
    region: "обл. София-град",
    datePosted: "16:30PM, 03.12",
    isVip: false,
    isTop: false,
  },
];
